// ---------------  scripts/updatePublications.mjs -----------------
import fetch from 'node-fetch';
import * as cheerio from 'cheerio';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

/* ── 1. 抓取 Scholar 列表 (一次拉 1000 条足够) ─────────────── */
const profileId = 'bSpZc84AAAAJ';
const url = `https://scholar.google.com/citations?hl=en&user=${profileId}&cstart=0&pagesize=1000`;
const html = await fetch(url).then(r => r.text());
const $ = cheerio.load(html);

/* ── 2. 解析每行 ──────────────────────────────────────────── */
const pubs = [];
$('tr.gsc_a_tr').each((_, el) => {
  const $el = $(el);
  const title = $el.find('a.gsc_a_at').text().trim();
  const paperPath = $el.find('a.gsc_a_at').attr('href') || '';
  const paperlink = paperPath ? `https://scholar.google.com${paperPath}` : '';
  const authors = $el.find('div.gs_gray').first().text().trim();
  const venue = $el.find('div.gs_gray').eq(1).text().trim();
  const year   = $el.find('span.gsc_a_hc').text().trim() ||
                 $el.find('span.gsc_a_y').text().trim();

  pubs.push({
    title,
    authors,
    conference: venue || year,
    paperlink,
    paperlinksmall: paperlink,
    imageSrc: '',      // 保留字段，与你现有 PublicationItem 对齐
    githublink: '',
    description: '',
    projectpage: '',
  });
});

/* ── 3. 写入 TS 源码 ───────────────────────────────────────── */
const banner = `/* AUTO-GENERATED by scripts/updatePublications.mjs */
import { PublicationItem } from './dataDef';
export const autoPublications: PublicationItem[] = `;
const targetPath = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/publications.generated.ts');
writeFileSync(targetPath, banner + JSON.stringify(pubs, null, 2) + ';', 'utf8');
console.log(`✅  ${pubs.length} publications saved to src/data/publications.generated.ts`);